### ISSUE TITLE
Can't use the "class" parameter in Hearthstone's card search because "class" is a reserved word in Python

### ISSUE THREAD

**Issue by MarvelSnapBoosters** [lostcol0ny/blizzardapi2#11]
The API is the card search method: https://develop.battle.net/documentation/hearthstone/game-data-apis

It has a parameter titled "class". I tried passing it as class='mage', but that failed because class is a reserved word in Python.

I tried passing {'class':'mage'} and got too many positional variables (as the code only looks for new arguments). I tried passing in query_params={'class':'mage'} just to test, but expectedly that sent query_params as the parameter within the dictionary. 

I edited the method "search_cards" in my own hearthstone_game_data_api.py to include the line "query_params.update({'class':'mage'}" and brute forcing in the parameter does now work. So just fully verifying the issue is with the parameter building for the query. 

Not saying this is how you should fix it, but could add a catch-all dict variable so if someone just passes in a dict it gets added to query_params within the method. So that just passing {'class':'mage'} would work, and would future proof this issue from popping up again.

**Comment by MarvelSnapBoosters** [comment]
This is personally how I did what I suggested. It will overwrite any of the definitions that follow in the call (so eg if you pass {'set':1} in the dic while also passing set=2 as a parameter, it will pass set as 1 to the Blizzard API)

```    
    def search_cards(
        self, region: str, locale: str, dic: dict, **query_params: Any
    ) -> Dict[str, Any]:
        resource = "/hearthstone/cards"
        query_params.update({"locale": locale})
        query_params = query_params | dic
        return super().get_resource(resource, region, query_params)
```

**Comment by lostcol0ny** [comment]
Thanks for the heads up! This is a fun edge case. I updated the code to handle this issue by adding in an optional `card_class` parameter to the search method arguments:

```
def search_cards(
    self, region: str, locale: str, card_class: str = None, **query_params: Any
) -> Dict[str, Any]:
```

The following usage should work for you now:

```
# Search for mage cards
cards = api_wrapper.search_cards(region="us", locale="en_US", card_class="mage")
```

This basically does what you suggested by appending the `card_class` value to `query_params` as the `class` parameter if it's present, and ignoring it if it's not.

I'm very much a hobbyist Python coder and this was super helpful. I'll update the package on PyPI today with the change. Since you have a working version, feel free to update to the new one when I push it or use the one you're using now. I have some work stuff coming up this morning but I'll try to get the package updated ASAP.

Thanks again! I'll keep this issue open until I have the new version pushed to PyPI.

**Comment by lostcol0ny** [comment]
blizzardapi2 version 1.1.2 has been pushed to PyPI. I'll close this one out now.
